version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    image: frontend-dev
    container_name: frontend-dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules



