FROM node:18-alpine
# use debian node ?

WORKDIR /home/apiserver
ENV NODE_ENV development

COPY package*.json yarn.lock ./

RUN yarn install


COPY . .
RUN npx prisma generate

EXPOSE 8000

CMD [ "yarn", "run", "dev" ]
